[project]
name = "whoknows"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.0",
    "numpy>=2.0",
    "python-dotenv>=1.0",
    "tokenizers>=0.21",
    "torch>=2.11",
    "torchao>=0.17",
    "wandb>=0.19",
]
